### PR TITLE
Implement `Display` for `Segment`

### PR DESCRIPTION
**Pull request by noib3**
## Problem

Working with the `Segments` iterator is a bit annoying because `Segment` doesn't implement `Display`.

## Solution

Implement `Display` for `Segment` and re-write the `Path`'s `Display` impl on top of it.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
Thank you for the PR!

Could you share an example of the code you are expecting to write using this impl? I am having a hard time envisioning how this is intended to be used.

**Comment by noib3** [comment]
Sure!

Here I'm using the `Segments` iterator to control whether the last segment gets printed. The entire `match` could be replaced by a `write!(f, ".{segment}")` if `Segment` implemented `Display`.

```rust
struct PathToError<'a> {
    err: &'a DeserializeError,
}

impl fmt::Display for PathToError<'_> {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.err.module_name)?;

        let segments = self.err.error.path().iter();

        let num_segments = segments.len();

        if num_segments == 0 {
            return Ok(());
        }

        let should_print_last_segment = matches!(
            self.err.error.inner(),
            Custom { .. } | UnknownVariant { .. }
        );

        for (idx, segment) in segments.enumerate() {
            let is_last = idx + 1 == num_segments;

            let should_print = !is_last | should_print_last_segment;

            if should_print {
                match segment {
                    Segment::Seq { index } => {
                        write!(f, ".[{}]", index)?;
                    },
                    Segment::Map { key } | Segment::Enum { variant: key } => {
                        write!(f, ".{}", key)?;
                    },
                    Segment::Unknown => {
                        write!(f, ".?")?;
                    },
                }
            }
        }

        Ok(())
    }
}
```

**Comment by dtolnay** [comment]
Got it. Looks good!

**Review by dtolnay — APPROVED** [review]

**Comment by dtolnay** [comment]
Published in 0.1.16.

**Pull request merged**
